const express = require('express');
const cors = require('cors');
require('dotenv').config();

// ✅ Import Sequelize models (index.js is auto-generated by sequelize-cli)
const db = require('../models');

// ✅ Import routes
const authRoutes = require('./routes/authRoutes');
// (you can later add more like roleRoutes, permissionRoutes, etc.)

const app = express();

// ✅ Middlewares
app.use(cors());
app.use(express.json());

// ✅ Health-check route
app.get('/', (req, res) => {
  res.send('✅ RBAC Backend is running...');
});

// ✅ Mount routes
app.use('/auth', authRoutes);

// ✅ Port from .env or default
const PORT = process.env.PORT || 5000;

// ✅ Connect to DB and sync models, then start server
db.sequelize.authenticate()
  .then(() => {
    console.log('✅ Database connected');
    return db.sequelize.sync(); // sync models & associations with database
  })
  .then(() => {
    app.listen(PORT, () => {
      console.log(`🚀 Server running on port ${PORT}`);
    });
  })
  .catch((err) => {
    console.error('❌ DB connection error:', err);
  });
